### ISSUE TITLE
Auth backend

### ISSUE THREAD

**Issue by cyberb** [syncloud-old/server#3]
User should be able to enter login/pass on device activation once and reuse it for all installed services.

Options:

1. Plain text master login/password. 
Problems:
1.1. Pain text
1.2. Password change is a problem

2. LDAP server.
Problems:
2.1. App servers may not support LDAP.

LDAP support:
ownCloud: natively
Gitlab: natively
Diaspora: through ldap plugin for Device (their auth backend)
Gitbucket: natively

**Comment by vsapronov** [comment]
This issue was moved to syncloud/platform#3
